swagger: "2.0"
info:
  description: "This is a dev server ImageResize server."
  version: "1.0.0"
  title: "Swagger ImageResize"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "83vilinyc6.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
  - "https"
  - "http"
paths:
  /imageResize:
    post:
      summary: Resize image and upload to s3
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image
          type: file
          description: Input image
      responses:
        "200":
          description: "Resize and upload to s3 successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "413":
          description: "Request Entity Too Large"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        example: "Incorrect mime"
  SuccessResponse:
    type: object
    properties:
      url:
        type: string
        example: "The public s3 link of uploaded and resized image"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"